<?php
namespace Tests\Feature\Inspections;
use App\Enums\{InspectionResponsibility as Role,InspectionStatus as Status,UserAccountType};use App\Models\{Inspection,Organization,User};use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
final class InspectionHttpTest extends TestCase {use RefreshDatabase;
 private function user(Organization $o,UserAccountType $type=UserAccountType::CompanyAdmin):User{return User::factory()->for($o)->create(['account_type'=>$type]);}
 private function inspection(Organization $o):Inspection{return Inspection::create(['organization_id'=>$o->id,'equipment_id'=>1,'inspection_type'=>'initial','status'=>'planned','context_snapshot'=>[]]);}
 public function test_admin_can_create_plan_assign_and_manage_references():void{$o=Organization::factory()->create();$admin=$this->user($o);$member=$this->user($o,UserAccountType::Member);$response=$this->actingAs($admin)->post(route('inspections.store'),['equipment_id'=>10,'inspection_type'=>'initial']);$i=Inspection::firstOrFail();$response->assertRedirect(route('inspections.show',$i));$this->actingAs($admin)->put(route('inspections.update',$i),['service_order'=>'OS-1'])->assertRedirect();$this->actingAs($admin)->post(route('inspections.responsibles.store',$i),['user_id'=>$member->id,'responsibility'=>'inspector','is_primary'=>true])->assertRedirect();$this->actingAs($admin)->post(route('inspections.references.store',$i),['equipment_document_id'=>77])->assertRedirect();$this->assertDatabaseHas('inspection_responsibles',['inspection_id'=>$i->id,'user_id'=>$member->id]);$this->assertDatabaseHas('inspection_reference_documents',['inspection_id'=>$i->id,'equipment_document_id'=>77]);}
 public function test_validation_and_capabilities_are_enforced():void{$o=Organization::factory()->create();$admin=$this->user($o);$member=$this->user($o,UserAccountType::Member);$i=$this->inspection($o);$this->actingAs($member)->post(route('inspections.store'),[])->assertForbidden();$this->actingAs($admin)->post(route('inspections.store'),[])->assertSessionHasErrors(['equipment_id','inspection_type']);$this->actingAs($admin)->post(route('inspections.start',$i))->assertForbidden();$this->actingAs($admin)->post(route('inspections.cancel',$i),['reason'=>'curta'])->assertSessionHasErrors('reason');}
 public function test_cross_tenant_bound_models_are_hidden():void{$a=Organization::factory()->create();$b=Organization::factory()->create();$admin=$this->user($a);$foreign=$this->inspection($b);$this->actingAs($admin)->get(route('inspections.show',$foreign))->assertNotFound();$this->actingAs($admin)->post(route('inspections.responsibles.store',$foreign),['user_id'=>$admin->id,'responsibility'=>'inspector'])->assertNotFound();}
 public function test_each_transition_endpoint_executes_with_formal_responsibility():void{$o=Organization::factory()->create();$admin=$this->user($o);$technical=$this->user($o,UserAccountType::Member);$i=$this->inspection($o);foreach(Role::cases() as $role){$this->actingAs($admin)->post(route('inspections.responsibles.store',$i),['user_id'=>$technical->id,'responsibility'=>$role->value])->assertRedirect();}$this->actingAs($technical)->post(route('inspections.start',$i))->assertRedirect();$this->actingAs($technical)->post(route('inspections.submit-for-review',$i))->assertRedirect();$this->actingAs($technical)->post(route('inspections.return-for-correction',$i),['reason'=>'Conteúdo técnico precisa ser corrigido.'])->assertRedirect();$this->actingAs($technical)->post(route('inspections.submit-for-review',$i))->assertRedirect();$this->actingAs($technical)->post(route('inspections.complete-review',$i))->assertRedirect();$this->actingAs($technical)->post(route('inspections.return-for-correction',$i),['reason'=>'A aprovação solicitou uma nova correção.'])->assertRedirect();$this->actingAs($technical)->post(route('inspections.submit-for-review',$i))->assertRedirect();$this->actingAs($technical)->post(route('inspections.complete-review',$i))->assertRedirect();$this->actingAs($technical)->post(route('inspections.approve',$i))->assertRedirect();$this->actingAs($technical)->post(route('inspections.release',$i))->assertRedirect();$this->assertSame(Status::Released,$i->refresh()->status);$this->assertDatabaseCount('inspection_status_histories',10);}
 public function test_cancel_endpoint_records_reason():void{$o=Organization::factory()->create();$admin=$this->user($o);$i=$this->inspection($o);$this->actingAs($admin)->post(route('inspections.cancel',$i),['reason'=>'Serviço cancelado formalmente pelo cliente.'])->assertRedirect();$this->assertDatabaseHas('inspection_status_histories',['inspection_id'=>$i->id,'to_status'=>'canceled','reason'=>'Serviço cancelado formalmente pelo cliente.']);}
}
